# Generated by ORMatic

from __future__ import annotations
from sqlalchemy import (
    Column,
    ForeignKey,
    Integer,
    String,
    Float,
    Boolean,
    DateTime,
    Enum,
    JSON,
    Table,
)
from sqlalchemy.orm import relationship, Mapped, mapped_column, DeclarativeBase

import builtins
import datetime
import enum
import krrood.adapters.json_serializer
import krrood.ormatic.custom_types
import krrood.ormatic.type_dict
import segmind.datastructures.event_plotter
import segmind.datastructures.events
import segmind.datastructures.mixins
import segmind.datastructures.object_tracker
import segmind.detectors.atomic_event_detectors_nodes
import segmind.detectors.base
import segmind.detectors.coarse_event_detector_nodes
import segmind.detectors.spatial_relation_detector_nodes
import segmind.episode_player
import segmind.episode_segmenter
import segmind.event_logger
import segmind.players.csv_player
import segmind.players.data_player
import segmind.players.json_player
import segmind.statecharts.segmind_statechart
import semantic_digital_twin.semantic_annotations.semantic_annotations
import semantic_digital_twin.world_description.world_entity
import sqlalchemy.sql.sqltypes
import typing
import typing_extensions
import uuid


from krrood.ormatic.data_access_objects.dao import (
    DataAccessObject,
    AssociationDataAccessObject,
)
from krrood.ormatic.custom_types import TypeType


class Base(DeclarativeBase):
    type_mappings = {
        typing.Type: krrood.ormatic.custom_types.TypeType,
        builtins.type: krrood.ormatic.custom_types.TypeType,
        enum.Enum: krrood.ormatic.custom_types.PolymorphicEnumType,
        krrood.adapters.json_serializer.SubclassJSONSerializer: sqlalchemy.sql.sqltypes.JSON,
        uuid.UUID: sqlalchemy.sql.sqltypes.UUID,
    }


# Association tables for many-to-many relationships


class AbstractDetectorDAO(
    Base, DataAccessObject[segmind.detectors.base.AbstractDetector]
):

    __tablename__ = "AbstractDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    name: Mapped[builtins.str] = mapped_column(
        sqlalchemy.sql.sqltypes.Text, use_existing_column=True
    )

    tracked_object: Mapped[
        typing.Optional[semantic_digital_twin.world_description.world_entity.Body]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )
    polymorphic_type: Mapped[str] = mapped_column(
        String(255), nullable=False, use_existing_column=True
    )

    __mapper_args__ = {
        "polymorphic_on": "polymorphic_type",
        "polymorphic_identity": "AbstractDetectorDAO",
    }


class AbstractInteractionDetectorDAO(
    AbstractDetectorDAO,
    DataAccessObject[
        segmind.detectors.coarse_event_detector_nodes.AbstractInteractionDetector
    ],
):

    __tablename__ = "AbstractInteractionDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "AbstractInteractionDetectorDAO",
        "inherit_condition": database_id == AbstractDetectorDAO.database_id,
    }


class BaseContainmentDetectorDAO(
    AbstractDetectorDAO,
    DataAccessObject[
        segmind.detectors.spatial_relation_detector_nodes.BaseContainmentDetector
    ],
):

    __tablename__ = "BaseContainmentDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    containment_threshold: Mapped[builtins.float] = mapped_column(
        use_existing_column=True
    )

    __mapper_args__ = {
        "polymorphic_identity": "BaseContainmentDetectorDAO",
        "inherit_condition": database_id == AbstractDetectorDAO.database_id,
    }


class ContactDetectorDAO(
    AbstractDetectorDAO,
    DataAccessObject[segmind.detectors.atomic_event_detectors_nodes.ContactDetector],
):

    __tablename__ = "ContactDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "ContactDetectorDAO",
        "inherit_condition": database_id == AbstractDetectorDAO.database_id,
    }


class ContainmentDetectorDAO(
    BaseContainmentDetectorDAO,
    DataAccessObject[
        segmind.detectors.spatial_relation_detector_nodes.ContainmentDetector
    ],
):

    __tablename__ = "ContainmentDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(BaseContainmentDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "ContainmentDetectorDAO",
        "inherit_condition": database_id == BaseContainmentDetectorDAO.database_id,
    }


class DetectionEventDAO(
    Base, DataAccessObject[segmind.datastructures.events.DetectionEvent]
):

    __tablename__ = "DetectionEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    timestamp: Mapped[datetime.datetime] = mapped_column(use_existing_column=True)

    polymorphic_type: Mapped[str] = mapped_column(
        String(255), nullable=False, use_existing_column=True
    )

    __mapper_args__ = {
        "polymorphic_on": "polymorphic_type",
        "polymorphic_identity": "DetectionEventDAO",
    }


class DetectorStateChartDAO(
    Base, DataAccessObject[segmind.detectors.base.DetectorStateChart]
):

    __tablename__ = "DetectorStateChartDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )


class EpisodePlayerDAO(Base, DataAccessObject[segmind.episode_player.EpisodePlayer]):

    __tablename__ = "EpisodePlayerDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    polymorphic_type: Mapped[str] = mapped_column(
        String(255), nullable=False, use_existing_column=True
    )

    __mapper_args__ = {
        "polymorphic_on": "polymorphic_type",
        "polymorphic_identity": "EpisodePlayerDAO",
    }


class DataPlayerDAO(
    EpisodePlayerDAO, DataAccessObject[segmind.players.data_player.DataPlayer]
):

    __tablename__ = "DataPlayerDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EpisodePlayerDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "DataPlayerDAO",
        "inherit_condition": database_id == EpisodePlayerDAO.database_id,
    }


class EpisodeSegmenterExecutorDAO(
    Base, DataAccessObject[segmind.episode_segmenter.EpisodeSegmenterExecutor]
):

    __tablename__ = "EpisodeSegmenterExecutorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    tmp_folder: Mapped[builtins.str] = mapped_column(
        sqlalchemy.sql.sqltypes.Text, use_existing_column=True
    )


class EventLoggerDAO(Base, DataAccessObject[segmind.event_logger.EventLogger]):

    __tablename__ = "EventLoggerDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    annotate_events: Mapped[builtins.bool] = mapped_column(use_existing_column=True)


class EventPlotterDAO(
    Base, DataAccessObject[segmind.datastructures.event_plotter.EventPlotter]
):

    __tablename__ = "EventPlotterDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )


class EventWithTrackedObjectsDAO(
    DetectionEventDAO,
    DataAccessObject[segmind.datastructures.events.EventWithTrackedObjects],
):

    __tablename__ = "EventWithTrackedObjectsDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(DetectionEventDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "EventWithTrackedObjectsDAO",
        "inherit_condition": database_id == DetectionEventDAO.database_id,
    }


class FilePlayerDAO(
    DataPlayerDAO, DataAccessObject[segmind.players.data_player.FilePlayer]
):

    __tablename__ = "FilePlayerDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(DataPlayerDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    file_path: Mapped[builtins.str] = mapped_column(
        sqlalchemy.sql.sqltypes.Text, use_existing_column=True
    )
    models_dir: Mapped[typing.Optional[builtins.str]] = mapped_column(
        sqlalchemy.sql.sqltypes.Text, use_existing_column=True
    )

    __mapper_args__ = {
        "polymorphic_identity": "FilePlayerDAO",
        "inherit_condition": database_id == DataPlayerDAO.database_id,
    }


class CSVEpisodePlayerDAO(
    FilePlayerDAO, DataAccessObject[segmind.players.csv_player.CSVEpisodePlayer]
):

    __tablename__ = "CSVEpisodePlayerDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(FilePlayerDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    data_object_names: Mapped[typing.Set[builtins.str]] = mapped_column(
        JSON, nullable=False, use_existing_column=True
    )

    __mapper_args__ = {
        "polymorphic_identity": "CSVEpisodePlayerDAO",
        "inherit_condition": database_id == FilePlayerDAO.database_id,
    }


class FrameDataDAO(Base, DataAccessObject[segmind.players.data_player.FrameData]):

    __tablename__ = "FrameDataDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    time: Mapped[builtins.float] = mapped_column(use_existing_column=True)
    frame_idx: Mapped[builtins.int] = mapped_column(use_existing_column=True)


class HasPrimaryTrackedObjectDAO(
    Base, DataAccessObject[segmind.datastructures.mixins.HasPrimaryTrackedObject]
):

    __tablename__ = "HasPrimaryTrackedObjectDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    tracked_object: Mapped[
        semantic_digital_twin.world_description.world_entity.Body
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=False, use_existing_column=True
    )
    polymorphic_type: Mapped[str] = mapped_column(
        String(255), nullable=False, use_existing_column=True
    )

    __mapper_args__ = {
        "polymorphic_on": "polymorphic_type",
        "polymorphic_identity": "HasPrimaryTrackedObjectDAO",
    }


class EventWithOneTrackedObjectDAO(
    EventWithTrackedObjectsDAO,
    DataAccessObject[segmind.datastructures.events.EventWithOneTrackedObject],
):

    __tablename__ = "EventWithOneTrackedObjectDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EventWithTrackedObjectsDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    tracked_object: Mapped[
        semantic_digital_twin.world_description.world_entity.Body
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=False, use_existing_column=True
    )

    __mapper_args__ = {
        "polymorphic_identity": "EventWithOneTrackedObjectDAO",
        "inherit_condition": database_id == EventWithTrackedObjectsDAO.database_id,
    }


class HasSecondaryTrackedObjectDAO(
    Base, DataAccessObject[segmind.datastructures.mixins.HasSecondaryTrackedObject]
):

    __tablename__ = "HasSecondaryTrackedObjectDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    with_object: Mapped[
        typing.Optional[semantic_digital_twin.world_description.world_entity.Body]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )
    polymorphic_type: Mapped[str] = mapped_column(
        String(255), nullable=False, use_existing_column=True
    )

    __mapper_args__ = {
        "polymorphic_on": "polymorphic_type",
        "polymorphic_identity": "HasSecondaryTrackedObjectDAO",
    }


class HasPrimaryAndSecondaryTrackedObjectsDAO(
    HasPrimaryTrackedObjectDAO,
    DataAccessObject[
        segmind.datastructures.mixins.HasPrimaryAndSecondaryTrackedObjects
    ],
):

    __tablename__ = "HasPrimaryAndSecondaryTrackedObjectsDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(HasPrimaryTrackedObjectDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    with_object: Mapped[
        typing.Optional[semantic_digital_twin.world_description.world_entity.Body]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )

    __mapper_args__ = {
        "polymorphic_identity": "HasPrimaryAndSecondaryTrackedObjectsDAO",
        "inherit_condition": database_id == HasPrimaryTrackedObjectDAO.database_id,
    }


class EventWithTwoTrackedObjectsDAO(
    EventWithTrackedObjectsDAO,
    DataAccessObject[segmind.datastructures.events.EventWithTwoTrackedObjects],
):

    __tablename__ = "EventWithTwoTrackedObjectsDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EventWithTrackedObjectsDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    with_object: Mapped[
        typing.Optional[semantic_digital_twin.world_description.world_entity.Body]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )
    tracked_object: Mapped[
        semantic_digital_twin.world_description.world_entity.Body
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=False, use_existing_column=True
    )

    __mapper_args__ = {
        "polymorphic_identity": "EventWithTwoTrackedObjectsDAO",
        "inherit_condition": database_id == EventWithTrackedObjectsDAO.database_id,
    }


class AbstractContactEventDAO(
    EventWithTwoTrackedObjectsDAO,
    DataAccessObject[segmind.datastructures.events.AbstractContactEvent],
):

    __tablename__ = "AbstractContactEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EventWithTwoTrackedObjectsDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "AbstractContactEventDAO",
        "inherit_condition": database_id == EventWithTwoTrackedObjectsDAO.database_id,
    }


class ContactEventDAO(
    AbstractContactEventDAO,
    DataAccessObject[segmind.datastructures.events.ContactEvent],
):

    __tablename__ = "ContactEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractContactEventDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "ContactEventDAO",
        "inherit_condition": database_id == AbstractContactEventDAO.database_id,
    }


class ContainmentEventDAO(
    EventWithTwoTrackedObjectsDAO,
    DataAccessObject[segmind.datastructures.events.ContainmentEvent],
):

    __tablename__ = "ContainmentEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EventWithTwoTrackedObjectsDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "ContainmentEventDAO",
        "inherit_condition": database_id == EventWithTwoTrackedObjectsDAO.database_id,
    }


class HasTrackedObjectsDAO(
    Base, DataAccessObject[segmind.datastructures.mixins.HasTrackedObjects]
):

    __tablename__ = "HasTrackedObjectsDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )


class InsertionDetectorDAO(
    AbstractDetectorDAO,
    DataAccessObject[
        segmind.detectors.spatial_relation_detector_nodes.InsertionDetector
    ],
):

    __tablename__ = "InsertionDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "InsertionDetectorDAO",
        "inherit_condition": database_id == AbstractDetectorDAO.database_id,
    }


class InsertionEventDAO(
    EventWithTwoTrackedObjectsDAO,
    DataAccessObject[segmind.datastructures.events.InsertionEvent],
):

    __tablename__ = "InsertionEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EventWithTwoTrackedObjectsDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    inserted_into_objects: Mapped[
        typing.List[semantic_digital_twin.world_description.world_entity.Body]
    ] = mapped_column(JSON, nullable=False, use_existing_column=True)

    __mapper_args__ = {
        "polymorphic_identity": "InsertionEventDAO",
        "inherit_condition": database_id == EventWithTwoTrackedObjectsDAO.database_id,
    }


class JSONPlayerDAO(
    FilePlayerDAO, DataAccessObject[segmind.players.json_player.JSONPlayer]
):

    __tablename__ = "JSONPlayerDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(FilePlayerDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    data_object_names: Mapped[typing.Set[builtins.str]] = mapped_column(
        JSON, nullable=False, use_existing_column=True
    )

    __mapper_args__ = {
        "polymorphic_identity": "JSONPlayerDAO",
        "inherit_condition": database_id == FilePlayerDAO.database_id,
    }


class LossOfContactDetectorDAO(
    AbstractDetectorDAO,
    DataAccessObject[
        segmind.detectors.atomic_event_detectors_nodes.LossOfContactDetector
    ],
):

    __tablename__ = "LossOfContactDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "LossOfContactDetectorDAO",
        "inherit_condition": database_id == AbstractDetectorDAO.database_id,
    }


class LossOfContactEventDAO(
    AbstractContactEventDAO,
    DataAccessObject[segmind.datastructures.events.LossOfContactEvent],
):

    __tablename__ = "LossOfContactEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractContactEventDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "LossOfContactEventDAO",
        "inherit_condition": database_id == AbstractContactEventDAO.database_id,
    }


class LossOfContainmentDetectorDAO(
    BaseContainmentDetectorDAO,
    DataAccessObject[
        segmind.detectors.spatial_relation_detector_nodes.LossOfContainmentDetector
    ],
):

    __tablename__ = "LossOfContainmentDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(BaseContainmentDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "LossOfContainmentDetectorDAO",
        "inherit_condition": database_id == BaseContainmentDetectorDAO.database_id,
    }


class LossOfContainmentEventDAO(
    EventWithTwoTrackedObjectsDAO,
    DataAccessObject[segmind.datastructures.events.LossOfContainmentEvent],
):

    __tablename__ = "LossOfContainmentEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EventWithTwoTrackedObjectsDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "LossOfContainmentEventDAO",
        "inherit_condition": database_id == EventWithTwoTrackedObjectsDAO.database_id,
    }


class LossOfSupportDetectorDAO(
    AbstractDetectorDAO,
    DataAccessObject[
        segmind.detectors.spatial_relation_detector_nodes.LossOfSupportDetector
    ],
):

    __tablename__ = "LossOfSupportDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "LossOfSupportDetectorDAO",
        "inherit_condition": database_id == AbstractDetectorDAO.database_id,
    }


class LossOfSupportEventDAO(
    EventWithTwoTrackedObjectsDAO,
    DataAccessObject[segmind.datastructures.events.LossOfSupportEvent],
):

    __tablename__ = "LossOfSupportEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EventWithTwoTrackedObjectsDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "LossOfSupportEventDAO",
        "inherit_condition": database_id == EventWithTwoTrackedObjectsDAO.database_id,
    }


class MotionDetectorDAO(
    AbstractDetectorDAO,
    DataAccessObject[segmind.detectors.atomic_event_detectors_nodes.MotionDetector],
):

    __tablename__ = "MotionDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    window_size: Mapped[builtins.int] = mapped_column(use_existing_column=True)
    rotation_threshold: Mapped[builtins.float] = mapped_column(use_existing_column=True)

    __mapper_args__ = {
        "polymorphic_identity": "MotionDetectorDAO",
        "inherit_condition": database_id == AbstractDetectorDAO.database_id,
    }


class MotionEventDAO(
    EventWithOneTrackedObjectDAO,
    DataAccessObject[segmind.datastructures.events.MotionEvent],
):

    __tablename__ = "MotionEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EventWithOneTrackedObjectDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    start_pose: Mapped[semantic_digital_twin.spatial_types.spatial_types.Pose] = (
        mapped_column(
            sqlalchemy.sql.sqltypes.JSON, nullable=False, use_existing_column=True
        )
    )
    current_pose: Mapped[semantic_digital_twin.spatial_types.spatial_types.Pose] = (
        mapped_column(
            sqlalchemy.sql.sqltypes.JSON, nullable=False, use_existing_column=True
        )
    )

    __mapper_args__ = {
        "polymorphic_identity": "MotionEventDAO",
        "inherit_condition": database_id == EventWithOneTrackedObjectDAO.database_id,
    }


class ObjectEventTrackerDAO(
    Base, DataAccessObject[segmind.datastructures.object_tracker.ObjectEventTracker]
):

    __tablename__ = "ObjectEventTrackerDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    body: Mapped[
        typing.Optional[semantic_digital_twin.world_description.world_entity.Body]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )

    context_id: Mapped[typing.Optional[builtins.int]] = mapped_column(
        ForeignKey("SegmindContextDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )

    context: Mapped[SegmindContextDAO] = relationship(
        "SegmindContextDAO", uselist=False, foreign_keys=[context_id], post_update=True
    )


class ObjectTrackerFactoryDAO(
    Base, DataAccessObject[segmind.datastructures.object_tracker.ObjectTrackerFactory]
):

    __tablename__ = "ObjectTrackerFactoryDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )


class PickUpDetectorDAO(
    AbstractInteractionDetectorDAO,
    DataAccessObject[segmind.detectors.coarse_event_detector_nodes.PickUpDetector],
):

    __tablename__ = "PickUpDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractInteractionDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "PickUpDetectorDAO",
        "inherit_condition": database_id == AbstractInteractionDetectorDAO.database_id,
    }


class PickUpEventDAO(
    EventWithOneTrackedObjectDAO,
    DataAccessObject[segmind.datastructures.events.PickUpEvent],
):

    __tablename__ = "PickUpEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EventWithOneTrackedObjectDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "PickUpEventDAO",
        "inherit_condition": database_id == EventWithOneTrackedObjectDAO.database_id,
    }


class PlacingDetectorDAO(
    AbstractInteractionDetectorDAO,
    DataAccessObject[segmind.detectors.coarse_event_detector_nodes.PlacingDetector],
):

    __tablename__ = "PlacingDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractInteractionDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "PlacingDetectorDAO",
        "inherit_condition": database_id == AbstractInteractionDetectorDAO.database_id,
    }


class PlacingEventDAO(
    EventWithTwoTrackedObjectsDAO,
    DataAccessObject[segmind.datastructures.events.PlacingEvent],
):

    __tablename__ = "PlacingEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EventWithTwoTrackedObjectsDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "PlacingEventDAO",
        "inherit_condition": database_id == EventWithTwoTrackedObjectsDAO.database_id,
    }


class RotationDetectorDAO(
    MotionDetectorDAO,
    DataAccessObject[segmind.detectors.atomic_event_detectors_nodes.RotationDetector],
):

    __tablename__ = "RotationDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(MotionDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "RotationDetectorDAO",
        "inherit_condition": database_id == MotionDetectorDAO.database_id,
    }


class RotationEventDAO(
    MotionEventDAO, DataAccessObject[segmind.datastructures.events.RotationEvent]
):

    __tablename__ = "RotationEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(MotionEventDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "RotationEventDAO",
        "inherit_condition": database_id == MotionEventDAO.database_id,
    }


class SegmindContextDAO(Base, DataAccessObject[segmind.detectors.base.SegmindContext]):

    __tablename__ = "SegmindContextDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    holes: Mapped[
        typing.List[
            semantic_digital_twin.semantic_annotations.semantic_annotations.Aperture
        ]
    ] = mapped_column(JSON, nullable=False, use_existing_column=True)

    logger_id: Mapped[int] = mapped_column(
        ForeignKey("EventLoggerDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )
    tracker_registry_id: Mapped[int] = mapped_column(
        ForeignKey("ObjectTrackerFactoryDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )

    logger: Mapped[EventLoggerDAO] = relationship(
        "EventLoggerDAO", uselist=False, foreign_keys=[logger_id], post_update=True
    )
    tracker_registry: Mapped[ObjectTrackerFactoryDAO] = relationship(
        "ObjectTrackerFactoryDAO",
        uselist=False,
        foreign_keys=[tracker_registry_id],
        post_update=True,
    )


class SegmindStatechartDAO(
    Base, DataAccessObject[segmind.statecharts.segmind_statechart.SegmindStatechart]
):

    __tablename__ = "SegmindStatechartDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )


class StopRotationDetectorDAO(
    MotionDetectorDAO,
    DataAccessObject[
        segmind.detectors.atomic_event_detectors_nodes.StopRotationDetector
    ],
):

    __tablename__ = "StopRotationDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(MotionDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "StopRotationDetectorDAO",
        "inherit_condition": database_id == MotionDetectorDAO.database_id,
    }


class StopRotationEventDAO(
    MotionEventDAO, DataAccessObject[segmind.datastructures.events.StopRotationEvent]
):

    __tablename__ = "StopRotationEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(MotionEventDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "StopRotationEventDAO",
        "inherit_condition": database_id == MotionEventDAO.database_id,
    }


class StopTranslationDetectorDAO(
    MotionDetectorDAO,
    DataAccessObject[
        segmind.detectors.atomic_event_detectors_nodes.StopTranslationDetector
    ],
):

    __tablename__ = "StopTranslationDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(MotionDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "StopTranslationDetectorDAO",
        "inherit_condition": database_id == MotionDetectorDAO.database_id,
    }


class StopTranslationEventDAO(
    MotionEventDAO, DataAccessObject[segmind.datastructures.events.StopTranslationEvent]
):

    __tablename__ = "StopTranslationEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(MotionEventDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "StopTranslationEventDAO",
        "inherit_condition": database_id == MotionEventDAO.database_id,
    }


class SupportDetectorDAO(
    AbstractDetectorDAO,
    DataAccessObject[segmind.detectors.spatial_relation_detector_nodes.SupportDetector],
):

    __tablename__ = "SupportDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "SupportDetectorDAO",
        "inherit_condition": database_id == AbstractDetectorDAO.database_id,
    }


class SupportEventDAO(
    EventWithTwoTrackedObjectsDAO,
    DataAccessObject[segmind.datastructures.events.SupportEvent],
):

    __tablename__ = "SupportEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EventWithTwoTrackedObjectsDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "SupportEventDAO",
        "inherit_condition": database_id == EventWithTwoTrackedObjectsDAO.database_id,
    }


class TranslationDetectorDAO(
    MotionDetectorDAO,
    DataAccessObject[
        segmind.detectors.atomic_event_detectors_nodes.TranslationDetector
    ],
):

    __tablename__ = "TranslationDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(MotionDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "TranslationDetectorDAO",
        "inherit_condition": database_id == MotionDetectorDAO.database_id,
    }


class TranslationEventDAO(
    MotionEventDAO, DataAccessObject[segmind.datastructures.events.TranslationEvent]
):

    __tablename__ = "TranslationEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(MotionEventDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "TranslationEventDAO",
        "inherit_condition": database_id == MotionEventDAO.database_id,
    }
